# name: Release a new version
#
# on:
#   push:
#     branches:
#       - master
#
# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
#       - name: Setup Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12
#       - run: npm install -g yarn
#       - name: Install dependencies
#         run: yarn
#       - name: Run tests
#         run: yarn test
#       - name: Release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#         run: npx semantic-release
